[package]
name = "Pyth"
version = "0.0.1"

[addresses]
pyth = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
